### ISSUE TITLE
Presentation Wiki

### ISSUE THREAD

**Issue by ianarsenault** [LynxMasters/Documentation#6]
Make a presentation wiki page that includes 

- [x] Proposal
- [x] Use Case Diagrams
- [x] Wireframes
- [x] Database Diagram

See [Midterm Presentation Wiki Page](https://github.com/LynxMasters/Documentation/wiki/Midterm-Presentation)

**Comment by j-arsenault** [comment]
Proposal (minus any changes tyler will make), and Use Case Diagrams have been added.

**Comment by ianarsenault** [comment]
Added all wireframes
